# Generated by Django 5.0.1 on 2024-01-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_memory_phone_owner_alter_phone_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
