# Generated by Django 5.0.1 on 2024-01-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
