# Generated by Django 5.0.1 on 2024-01-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_alter_memory_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='phones',
        ),
    ]
